Changed `android:multiArch` to `"false"` false since our bundle has single ABI
Starting from Android 15 a verification during install had been added. If the verification fails, it gives
	Error: INSTALL_FAILED_INTERNAL_ERROR: Error deriving application ABI: The multiArch app's native libs don't support all the natively supported ABIs of the device.

Related Android commit:
https://android.googlesource.com/platform/frameworks/base/+/a55ab0340e16baa56e79c22688c349cc327a3361

	[PM] Force multi-arch app native libs match natively ABIs

	Force the match when the below conditions are satisfied
	1. When the feature flag is On.
	2. It is an multi-arch APP `android:multiarch = true` in its manifest
	3. The targetSdkVersion of the apk >= VANILLA_ICE_CREAM
	4. The installation is not the cpuAbiOverride case.

	The match rule:
	1.If the system supports 32 bit abi, but there is no native library
	matching natively 32 bit abis
	2. If the system supports 64 bit abi, but there is no native library
	matching natively 64 bit abis

	Test: atest CtsSliceTestCases
	Test: atest CtsAppTestStubsApp2
	Test: atest CtsWidgetTestCases
	Test: atest CtsInputMethodTestCases
	Test: atest CtsOsHostTestCases
	Test: atest CtsPackageManagerHostTestCases
	Test: atest CtsDisplayTestCases
	Test: atest CtsPackageManagerTestCases
	Test: atest CtsAppEnumerationTestCases
	Bug: 282783453
	Change-Id: I8bbda14786be6bb7ad8d4fae80c7426ec7af71b2