Avoid redefinition of the cr-toolbar name for history page
Upstream re-introduced a cr_toolbar.js import in history_toolbar.ts,
which collides with our br_toolbar.m.js, which also defines cr-toolbar,
causing a Javascript error when opening the history page like this:

  Uncaught NotSupportedError: Failed to execute 'define' on 'CustomElementRegistry':
  the name "cr-toolbar" has already been used with this registry",
  source: chrome://history/ (0)

Remove that import to get the history page working again.

Chromium change:

https://source.chromium.org/chromium/chromium/src/+/f3907c07a8a0c13b1b513f507719fe3e316d8c80

commit f3907c07a8a0c13b1b513f507719fe3e316d8c80
Author: dpapad <dpapad@chromium.org>
Date:   Wed May 26 17:41:25 2021 +0000

    History: Migrate to TypeScript.

     - Remove js_library(), js_type_check() targets.
     - Add new ts_library() target, and hook it up to the build.
     - Migrate all files to TypeScript, and fix all errors.
     - Override default tsconfig with a few options that seem necessary
       for Polymer code.
     - Introduce EventTracker usage in app.ts as part of the migration
       (easier than adding type info for boundOnKeyDown_)
     - Rename 'open-menu' event to 'synced-device-card-open-menu' in
       synced_device_card.ts, to be able to differentiate with the
       'open-menu' event in history_card.ts, when declaring the Event type
       in the global HTMLElementEventMap.

    Bug: 1189595